version: '3.8'
services:
  app:
    image: haidang218/learn-cicd:latest
    container_name: learn-cicd-app
    env_file:
      - .env
    ports:  
      - "${PORT}:5005"
    restart: unless-stopped
    